name: Repo Sync

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: veggiss/testrepo
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.VEGGIS2_PAT }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: repo_sync
        destination_branch: main
        github_token: ${{ secrets.VEGGIS2_PAT }}
