on:
  push:
    branches:
    - main
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_repository: veggiss2/workflowtest
        destination_branch: "main"
        github_token: ${{ secrets.VEGGIS2_PAT }}
    - name: output-url
      run: echo ${{steps.open-pr.outputs.pr_url}}
    - name: output-number
      run: echo ${{steps.open-pr.outputs.pr_number}}
    - name: output-created
      run: echo ${{steps.open-pr.outputs.pr_created}}
    - name: output-has-changed-files
      run: echo ${{steps.open-pr.outputs.has_changed_files}}
