name: Push to main branch
on:
  push:
    branches:
      - main
jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Push changes
        env:
          PAT: ${{ secrets.VEGGIS2_PAT }}
        run: |
          git remote add dest https://github.com/veggiss2/workflowtest.git
          git fetch dest main
          git merge --no-commit --no-ff dest/main
          git commit -m "Merge changes from veggiss/testrepo" || true
          git push https://$PAT@github.com/veggiss/testrepo.git HEAD:main --allow-unrelated-histories
