name: Push to main branch
on:
  push:
    branches:
      - main
jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push changes
        env:
          PAT: ${{ secrets.VEGGIS2_PAT }}
        run: |
          echo "1 remote add dest"
          git remote add dest https://github.com/veggiss2/workflowtest.git
          echo "2 fetch dest main"
          git fetch dest main
          echo "3 pull dest main"
          git pull dest main --no-ff --allow-unrelated-histories
          echo "4 git reset .github"
          git reset .github/*
          echo "5 push dest main"
          git push dest main
