name: Push to main branch
on:
  push:
    branches:
      - main
jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Push changes
        env:
          PAT: ${{ secrets.VEGGIS2_PAT }}
        run: |
          echo "remote add dest"
          git remote add dest https://github.com/veggiss2/workflowtest.git
          echo "fetch dest main"
          git fetch dest main
          echo "merge --no-ff --no-commit"
          git merge --no-ff --no-commit --allow-unrelated-histories dest/main
          echo "reset .github/*"
          git reset .github/*
          echo "commit"
          git commit -m "Merge changes from veggiss/testrepo" || true
          echo "push"
          git push dest main
