name: Pull from External Branch

on:
  push: # Trigger the workflow on a push event
    branches:
      - main # Only trigger the workflow when the main is pushed to

jobs:
  pull-external-branch:
    runs-on: ubuntu-latest # Run the job on an Ubuntu environment

    steps:
    - name: Checkout code # Check out the code into the runner environment
      uses: actions/checkout@v3

    - name: Pull from External Branch # Pull the external branch into the current repository
      uses: repo-sync/github-sync@v2 # Use the repo-sync/pull-repo action
      with:
        source_repo: veggiss2/workflowtest # The owner and repository name of the external repository
        source_branch: main # The name of the branch to pull from the external repository
        destination_branch: main # The name of the branch to merge the external branch into in the current repository
        github_token: ${{ secrets.PAT }} # The personal access token used to authenticate with the external repository
